version: "3"

services:

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
      environment:
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
          - http.host=0.0.0.0
          - transport.host=0.0.0.0
      ports:
          - "9200:9200"
      volumes:
          - ./elasticsearch_data:/usr/share/elasticsearch/data
          # - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

    kibana:
      image: docker.elastic.co/kibana/kibana:8.3.3
      ports:
          - "5601:5601"
      environment:
          ELASTICSEARCH_URL: http://elasticsearch:9200
          ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      # volumes:
      #     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      depends_on:
          - elasticsearch

    logstash:
      image: docker.elastic.co/logstash/logstash:8.3.3
      volumes:
        # - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        - ./logstash/pipeline:/usr/share/logstash/pipeline
      ports:
        - "5044:5044"
        - "5010:5010/tcp"
        - "5010:5010/udp"
        - "9600:9600"
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      # depends_on:
      #   - elasticsearch
